/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio Memory API
 * APIs for managing memory stores, profiles, events, and conversational intelligence capabilities.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { inspect, InspectOptions } from "util";
import V1 from "../V1";
const deserialize = require("../../../base/deserialize");
const serialize = require("../../../base/serialize");
import { isValidPathParam } from "../../../base/utility";
import { ApiResponse } from "../../../base/ApiResponse";

/**
 * Data for creating or updating a profile, including traits.
 */
export class ProfileData {
  /**
   * Multiple trait groups.
   */
  "traits"?: { [key: string]: { [key: string]: any } };

  constructor(payload) {
    this.traits = payload["traits"];
  }
}

export class UpdateProfilesBulkRequest {
  "profiles"?: Array<ProfileData>;

  constructor(payload) {
    this.profiles = payload["profiles"];
  }
}

/**
 * Options to pass to update a BulkInstance
 */
export interface BulkContextUpdateOptions {
  /**  */
  updateProfilesBulkRequest: UpdateProfilesBulkRequest;
}

export interface BulkContext {
  /**
   * Update a BulkInstance
   *
   * @param params - Body for request
   * @param headers - header params for request
   * @param callback - Callback to handle processed record
   *
   * @returns Resolves to processed BulkInstance
   */
  update(
    params: UpdateProfilesBulkRequest,
    headers?: any,
    callback?: (error: Error | null, item?: BulkInstance) => any
  ): Promise<BulkInstance>;

  /**
   * Update a BulkInstance and return HTTP info
   *
   * @param params - Body for request
   * @param headers - header params for request
   * @param callback - Callback to handle processed record
   *
   * @returns Resolves to processed BulkInstance with HTTP metadata
   */
  updateWithHttpInfo(
    params: UpdateProfilesBulkRequest,
    headers?: any,
    callback?: (error: Error | null, item?: ApiResponse<BulkInstance>) => any
  ): Promise<ApiResponse<BulkInstance>>;

  /**
   * Provide a user-friendly representation
   */
  toJSON(): any;
  [inspect.custom](_depth: any, options: InspectOptions): any;
}

export interface BulkContextSolution {
  storeId: string;
}

export class BulkContextImpl implements BulkContext {
  protected _solution: BulkContextSolution;
  protected _uri: string;

  constructor(protected _version: V1, storeId: string) {
    if (!isValidPathParam(storeId)) {
      throw new Error("Parameter 'storeId' is not valid.");
    }

    this._solution = { storeId };
    this._uri = `/Stores/${storeId}/Profiles/Bulk`;
  }

  update(
    params: UpdateProfilesBulkRequest,
    headers?: any,
    callback?: (error: Error | null, item?: BulkInstance) => any
  ): Promise<BulkInstance> {
    if (params === null || params === undefined) {
      throw new Error('Required parameter "params" missing.');
    }

    let data: any = {};

    data = params;

    if (headers === null || headers === undefined) {
      headers = {};
    }

    headers["Content-Type"] = "application/json";
    headers["Accept"] = "application/json";

    const instance = this;
    let operationVersion = instance._version,
      operationPromise = operationVersion.update({
        uri: instance._uri,
        method: "put",
        data,
        headers,
      });

    operationPromise = operationPromise.then(
      (payload) =>
        new BulkInstance(operationVersion, payload, instance._solution.storeId)
    );

    operationPromise = instance._version.setPromiseCallback(
      operationPromise,
      callback
    );
    return operationPromise;
  }

  updateWithHttpInfo(
    params: UpdateProfilesBulkRequest,
    headers?: any,
    callback?: (error: Error | null, item?: ApiResponse<BulkInstance>) => any
  ): Promise<ApiResponse<BulkInstance>> {
    if (params === null || params === undefined) {
      throw new Error('Required parameter "params" missing.');
    }

    let data: any = {};

    data = params;

    if (headers === null || headers === undefined) {
      headers = {};
    }

    headers["Content-Type"] = "application/json";
    headers["Accept"] = "application/json";

    const instance = this;
    let operationVersion = instance._version;
    // CREATE, FETCH, UPDATE operations
    let operationPromise = operationVersion
      .updateWithResponseInfo<BulkResource>({
        uri: instance._uri,
        method: "put",
        data,
        headers,
      })
      .then(
        (response): ApiResponse<BulkInstance> => ({
          ...response,
          body: new BulkInstance(
            operationVersion,
            response.body,
            instance._solution.storeId
          ),
        })
      );

    operationPromise = instance._version.setPromiseCallback(
      operationPromise,
      callback
    );
    return operationPromise;
  }

  /**
   * Provide a user-friendly representation
   *
   * @returns Object
   */
  toJSON() {
    return this._solution;
  }

  [inspect.custom](_depth: any, options: InspectOptions) {
    return inspect(this.toJSON(), options);
  }
}

interface BulkResource {
  message: string;
}

export class BulkInstance {
  protected _solution: BulkContextSolution;
  protected _context?: BulkContext;

  constructor(
    protected _version: V1,
    _payload: BulkResource,
    storeId?: string
  ) {
    const payload = _payload;
    this.message = payload.message;

    this._solution = { storeId: storeId };
  }

  message: string;

  private get _proxy(): BulkContext {
    this._context =
      this._context ||
      new BulkContextImpl(this._version, this._solution.storeId);
    return this._context;
  }

  /**
   * Update a BulkInstance
   *
   * @param params - Body for request
   * @param headers - header params for request
   * @param callback - Callback to handle processed record
   *
   * @returns Resolves to processed BulkInstance
   */
  update(
    params: UpdateProfilesBulkRequest,
    headers?: any,
    callback?: (error: Error | null, item?: BulkInstance) => any
  ): Promise<BulkInstance>;

  update(
    params?: any,
    callback?: (error: Error | null, item?: BulkInstance) => any
  ): Promise<BulkInstance> {
    return this._proxy.update(params, callback);
  }

  /**
   * Update a BulkInstance and return HTTP info
   *
   * @param params - Body for request
   * @param headers - header params for request
   * @param callback - Callback to handle processed record
   *
   * @returns Resolves to processed BulkInstance with HTTP metadata
   */
  updateWithHttpInfo(
    params: UpdateProfilesBulkRequest,
    headers?: any,
    callback?: (error: Error | null, item?: ApiResponse<BulkInstance>) => any
  ): Promise<ApiResponse<BulkInstance>>;

  updateWithHttpInfo(
    params?: any,
    callback?: (error: Error | null, item?: ApiResponse<BulkInstance>) => any
  ): Promise<ApiResponse<BulkInstance>> {
    return this._proxy.updateWithHttpInfo(params, callback);
  }

  /**
   * Provide a user-friendly representation
   *
   * @returns Object
   */
  toJSON() {
    return {
      message: this.message,
    };
  }

  [inspect.custom](_depth: any, options: InspectOptions) {
    return inspect(this.toJSON(), options);
  }
}

export interface BulkSolution {}

export interface BulkListInstance {
  _version: V1;
  _solution: BulkSolution;
  _uri: string;

  (storeId: string): BulkContext;
  get(storeId: string): BulkContext;

  /**
   * Provide a user-friendly representation
   */
  toJSON(): any;
  [inspect.custom](_depth: any, options: InspectOptions): any;
}

export function BulkListInstance(version: V1): BulkListInstance {
  const instance = ((storeId) => instance.get(storeId)) as BulkListInstance;

  instance.get = function get(storeId): BulkContext {
    return new BulkContextImpl(version, storeId);
  };

  instance._version = version;
  instance._solution = {};
  instance._uri = ``;

  instance.toJSON = function toJSON() {
    return instance._solution;
  };

  instance[inspect.custom] = function inspectImpl(
    _depth: any,
    options: InspectOptions
  ) {
    return inspect(instance.toJSON(), options);
  };

  return instance;
}
