/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Insights
 * Insights Domain V3 API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import InsightsBase from "../InsightsBase";
import Version from "../../base/Version";
import { MetadataListInstance } from "./v3/metadata";
import { QueryListInstance } from "./v3/query";

export default class V3 extends Version {
  /**
   * Initialize the V3 version of Insights
   *
   * @param domain - The Twilio (Twilio.Insights) domain
   */
  constructor(domain: InsightsBase) {
    super(domain, "v3");
  }

  /** metadata - { Twilio.Insights.V3.MetadataListInstance } resource */
  protected _metadata?: MetadataListInstance;
  /** query - { Twilio.Insights.V3.QueryListInstance } resource */
  protected _query?: QueryListInstance;

  /** Getter for metadata resource */
  get metadata(): MetadataListInstance {
    this._metadata = this._metadata || MetadataListInstance(this);
    return this._metadata;
  }

  /** Getter for query resource */
  get query(): QueryListInstance {
    this._query = this._query || QueryListInstance(this);
    return this._query;
  }
}
